insert into posts (id, title, author) values (1, 'Our Sunhi', 'Marina Armfield');
insert into posts (id, title, author) values (2, 'Adventures of Arsène Lupin, The (Aventures d''Arsène Lupin, Les)', 'Joyous Codner');
insert into posts (id, title, author) values (3, 'Pajeczarki', 'Carmine Saveall');
insert into posts (id, title, author) values (4, 'Strictly Ballroom', 'Muffin Wardesworth');
insert into posts (id, title, author) values (5, 'Scorpio', 'Rockwell Rosenstein');
insert into posts (id, title, author) values (6, 'Legend of the Lone Ranger, The', 'Suzy Thornthwaite');
insert into posts (id, title, author) values (7, 'Yes: 9012 Live', 'Laraine McPhelimy');
insert into posts (id, title, author) values (8, 'Ladies Man, The', 'Stanwood Ludlam');
insert into posts (id, title, author) values (9, 'Dolce Vita, La', 'Joline Sweatman');
insert into posts (id, title, author) values (10, 'Dogtown and Z-Boyz', 'Melisande Farady');
insert into posts (id, title, author) values (11, 'The Trip to Squash Land', 'Brunhilda Spargo');
insert into posts (id, title, author) values (12, 'Jules and Jim (Jules et Jim)', 'Hilliary MacDaid');
insert into posts (id, title, author) values (13, 'Alice in Wonderland', 'Ki Jedryka');
insert into posts (id, title, author) values (14, 'Xingu ', 'Jonah Steedman');
insert into posts (id, title, author) values (15, 'Frozen Assets', 'Mirabella Pipes');
insert into posts (id, title, author) values (16, 'Dancer Upstairs, The', 'Cornie Danielsky');
insert into posts (id, title, author) values (17, 'The Uncommon Making of Petulia', 'Marga Cramphorn');
insert into posts (id, title, author) values (18, 'Dom Hemingway', 'Gertruda Mowbury');
insert into posts (id, title, author) values (19, 'Sergeant Körmy and the Underwater Vehicles (Vääpeli Körmy ja vetenalaiset vehkeet)', 'Lynnell Jarrette');
insert into posts (id, title, author) values (20, 'Mirror Mirror', 'Elane Sandall');


insert into comments (id, author, content, post_id) values (1, 'Meryl Barabich', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna', 1);
insert into comments (id, author, content, post_id) values (2, 'Tabbie Rontree', 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', 1);
insert into comments (id, author, content, post_id) values (3, 'Casi Thwaites', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 1);
insert into comments (id, author, content, post_id) values (4, 'Vere Fochs', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 2);
insert into comments (id, author, content, post_id) values (5, 'Gizela Coveny', 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo', 2);
insert into comments (id, author, content, post_id) values (6, 'Newton Burnup', 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 2);
insert into comments (id, author, content, post_id) values (7, 'Karrie Dauby', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 3);
insert into comments (id, author, content, post_id) values (8, 'Calli Loakes', 'venenatis turpis enim blandit mi in porttitor pede justo eu massa', 3);
insert into comments (id, author, content, post_id) values (9, 'Bertram Gibb', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 3);
insert into comments (id, author, content, post_id) values (10, 'Jammie Jimpson', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 3);
insert into comments (id, author, content, post_id) values (11, 'Rorke Dellit', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 4);
insert into comments (id, author, content, post_id) values (12, 'Ethe Moyles', 'ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam', 4);
insert into comments (id, author, content, post_id) values (13, 'Emmery Pllu', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 5);
insert into comments (id, author, content, post_id) values (14, 'Noam Gibling', 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', 6);
insert into comments (id, author, content, post_id) values (15, 'Dwight Collough', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 6);
insert into comments (id, author, content, post_id) values (16, 'Gwyn Pogson', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', 6);
insert into comments (id, author, content, post_id) values (17, 'Hunt Gatchell', 'quis lectus suspendisse potenti in eleifend quam a odio in hac', 6);
insert into comments (id, author, content, post_id) values (18, 'Raleigh McGrouther', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 6);
insert into comments (id, author, content, post_id) values (19, 'Currey Aishford', 'ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu',7);
insert into comments (id, author, content, post_id) values (20, 'Meredith Speere', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque',7);
